
obj-y = bitmap.o exthdrs_core.o find_last_bit.o find_next_bit.o hexdump.o kasprintf.o kstrtox.o  rcutiny.o seq_file.o time.o timer.o vsprintf.o net_namespace.o idr.o


ccflags-y = -I. -I/usr/src/linux-3.2.68/debian/build/source_rt/include -fno-omit-frame-pointer -pg

